"""Second Migration

Revision ID: 8f2228bfe183
Revises: 5fabf50a3be6
Create Date: 2019-02-21 20:18:35.238182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2228bfe183'
down_revision = '5fabf50a3be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('destination', sa.Text(), nullable=True),
    sa.Column('date_to', sa.Text(), nullable=True),
    sa.Column('date_from', sa.Text(), nullable=True),
    sa.Column('adults', sa.Integer(), nullable=True),
    sa.Column('infants', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
